spring:
  datasource:
    druid:
      #  JDBC 配置
      #driver-class-name: com.alibaba.druid.pool.DruidDataSource
      #driver-class-name: net.sf.log4jdbc.DriverSpy
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:log4jdbc:mysql://10.130.0.37:3307/jwwl_attachment?useUnicode=true&characterEncoding=utf-8
      url: jdbc:mysql://127.0.0.1:3306/auth-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root@123
      # 连接池配置
      initial-size: 10
      max-active: 20
      max-evictable-idle-time-millis: 60000
      max-open-prepared-statements: 60000
      max-pool-prepared-statement-per-connection-size: 10
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 10000
      filters: stat,wall,log4j2  # 配置监控统计拦截的filters,采用log4j2作为日志实现
      # 监控配置　WebStatFilter配置
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        # principal-cookie-name: ''
        #principal-session-name: ''
        #profile-enable: ''
        #session-stat-enable: ''
        #session-stat-max-count: ''
        #url-pattern: ''
      stat-view-servlet:
        allow: 127.0.0.1  # IP 白名单
        deny: 192.168.0.10 #  IP黑名单(共同存在时，deny优先于allow)
        enabled: true
        login-password: admin  # 控制台用户名和密码
        login-username: admin
        reset-enable: false

  jpa.:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      # update：表示自动根据model对象来更新表结构，启动 hibernate 时会自动检查数据库，如果缺少表则自动建表；缺少列则自动添加列；
      # create： 启动hibernate时，自动删除原来的表，新建所有的表，所以每次启动后的以前数据都会丢失。
      # create-drop：应用停下来的时候，自动会把表和数据删掉、
      # none： 什么也不做；
      # validate：会验证类里的属性和表字段是否一致，不一致，则会报错；
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



